# Generated by Django 5.2.3 on 2025-06-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_type_remove_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
