# Generated by Django 5.2.3 on 2025-06-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
    ]
