# Generated by Django 5.2.3 on 2025-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_event', 'Новое мероприятие'), ('event_updated', 'Мероприятие обновлено'), ('event_cancelled', 'Мероприятие отменено'), ('event_unpublished', 'Мероприятие снято с публикации'), ('event_approved', 'Мероприятие одобрено'), ('event_rejected', 'Мероприятие отклонено'), ('new_participant', 'Новый участник'), ('participant_cancelled', 'Участник отменил регистрацию')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
