# Generated by Django 5.2.3 on 2025-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_cancelled', 'Мероприятие отменено'), ('event_time_changed', 'Время мероприятия изменено'), ('event_unpublished', 'Мероприятие снято с публикации')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
